import {
  BadgeDollarSign,
  Bike,
  Briefcase,
  Building2,
  Bus,
  CalendarHeart,
  Camera,
  Car,
  CarFront,
  Castle,
  ChefHat,
  Clapperboard,
  Compass,
  GraduationCap,
  Hammer,
  Heart,
  Home as HomeIcon,
  Hotel,
  Landmark,
  Laptop,
  Map,
  Mountain,
  Music,
  Palmtree,
  PartyPopper,
  Ship,
  Sparkles,
  Store,
  Truck,
  Users,
  UtensilsCrossed,
  Warehouse,
  Wine,
  Wrench,
} from "lucide-react";

export const buildPublicNavLinks = (t) => [
  {
    name: t("nav.realEstate", "Bienes Raíces"),
    path: "/buscar?resourceType=property&operationType=sale",
    items: [
      {
        icon: HomeIcon,
        label: t("nav.dropdown.houses", "Casas"),
        desc: t("nav.dropdown.housesDesc", "Casas en venta en las mejores zonas"),
        to: "/buscar?resourceType=property&operationType=sale&propertyType=house",
      },
      {
        icon: Building2,
        label: t("nav.dropdown.apartments", "Departamentos"),
        desc: t("nav.dropdown.apartmentsDesc", "Departamentos y condominios"),
        to: "/buscar?resourceType=property&operationType=sale&propertyType=apartment",
      },
      {
        icon: Landmark,
        label: t("nav.dropdown.land", "Terrenos"),
        desc: t("nav.dropdown.landDesc", "Terrenos listos para construir"),
        to: "/buscar?resourceType=property&operationType=sale&propertyType=land",
      },
      {
        icon: Store,
        label: t("nav.dropdown.commercial", "Comercial"),
        desc: t("nav.dropdown.commercialDesc", "Locales y oficinas comerciales"),
        to: "/buscar?resourceType=property&operationType=sale&propertyType=commercial",
      },
      {
        icon: Briefcase,
        label: t("nav.dropdown.offices", "Oficinas"),
        desc: t("nav.dropdown.officesDesc", "Oficinas en zonas estratégicas"),
        to: "/buscar?resourceType=property&operationType=sale&propertyType=office",
      },
      {
        icon: Warehouse,
        label: t("nav.dropdown.warehouses", "Bodegas"),
        desc: t("nav.dropdown.warehousesDesc", "Bodegas y naves industriales"),
        to: "/buscar?resourceType=property&operationType=sale&propertyType=warehouse",
      },
    ],
  },
  {
    name: t("nav.vacation", "Rentas Vacacionales"),
    path: "/buscar?resourceType=property&operationType=vacation_rental",
    items: [
      {
        icon: Hotel,
        label: t("nav.dropdown.hotels", "Hoteles"),
        desc: t("nav.dropdown.hotelsDesc", "Alojamiento en hoteles de la zona"),
        to: "/buscar?resourceType=property&operationType=vacation_rental",
      },
      {
        icon: Castle,
        label: t("nav.dropdown.condos", "Condominios"),
        desc: t("nav.dropdown.condosDesc", "Condominios para estancias cortas"),
        to: "/buscar?resourceType=property&operationType=vacation_rental&propertyType=apartment",
      },
      {
        icon: Palmtree,
        label: t("nav.dropdown.villas", "Villas"),
        desc: t("nav.dropdown.villasDesc", "Villas de lujo para vacaciones"),
        to: "/buscar?resourceType=property&operationType=vacation_rental&propertyType=house",
      },
      {
        icon: BadgeDollarSign,
        label: t("nav.dropdown.budget", "Económicas"),
        desc: t("nav.dropdown.budgetDesc", "Opciones accesibles para todos"),
        to: "/buscar?resourceType=property&operationType=vacation_rental&sort=price-asc",
      },
    ],
  },
  {
    name: t("nav.vehicles", "Vehículos"),
    path: "/buscar?resourceType=vehicle",
    items: [
      {
        icon: Car,
        label: t("nav.dropdown.vehicleCar", "Autos"),
        desc: t("nav.dropdown.vehicleCarDesc", "Autos compactos y sedanes"),
        to: "/buscar?resourceType=vehicle&propertyType=car",
      },
      {
        icon: CarFront,
        label: t("nav.dropdown.vehicleSuv", "SUVs"),
        desc: t("nav.dropdown.vehicleSuvDesc", "Camionetas y SUVs familiares"),
        to: "/buscar?resourceType=vehicle&propertyType=suv",
      },
      {
        icon: Truck,
        label: t("nav.dropdown.vehiclePickup", "Pickups"),
        desc: t("nav.dropdown.vehiclePickupDesc", "Pickups para trabajo y aventura"),
        to: "/buscar?resourceType=vehicle&propertyType=pickup",
      },
      {
        icon: Bus,
        label: t("nav.dropdown.vehicleVan", "Vans"),
        desc: t("nav.dropdown.vehicleVanDesc", "Vans y transporte de pasajeros"),
        to: "/buscar?resourceType=vehicle&propertyType=van",
      },
      {
        icon: Bike,
        label: t("nav.dropdown.vehicleMotorcycle", "Motos"),
        desc: t("nav.dropdown.vehicleMotorcycleDesc", "Motocicletas y scooters"),
        to: "/buscar?resourceType=vehicle&propertyType=motorcycle",
      },
      {
        icon: Ship,
        label: t("nav.dropdown.vehicleBoat", "Embarcaciones"),
        desc: t("nav.dropdown.vehicleBoatDesc", "Lanchas, yates y veleros"),
        to: "/buscar?resourceType=vehicle&propertyType=boat",
      },
    ],
  },
  {
    name: t("nav.services", "Servicios"),
    path: "/buscar?resourceType=service",
    items: [
      {
        icon: Sparkles,
        label: t("nav.dropdown.serviceCleaning", "Limpieza"),
        desc: t("nav.dropdown.serviceCleaningDesc", "Limpieza profesional para tu espacio"),
        to: "/buscar?resourceType=service&propertyType=cleaning",
      },
      {
        icon: Music,
        label: t("nav.dropdown.serviceDj", "DJ"),
        desc: t("nav.dropdown.serviceDjDesc", "DJs para fiestas y eventos"),
        to: "/buscar?resourceType=service&propertyType=dj",
      },
      {
        icon: ChefHat,
        label: t("nav.dropdown.serviceChef", "Chef"),
        desc: t("nav.dropdown.serviceChefDesc", "Chefs privados a domicilio"),
        to: "/buscar?resourceType=service&propertyType=chef",
      },
      {
        icon: Camera,
        label: t("nav.dropdown.servicePhotography", "Fotografía"),
        desc: t("nav.dropdown.servicePhotographyDesc", "Fotógrafos profesionales"),
        to: "/buscar?resourceType=service&propertyType=photography",
      },
      {
        icon: UtensilsCrossed,
        label: t("nav.dropdown.serviceCatering", "Catering"),
        desc: t("nav.dropdown.serviceCateringDesc", "Banquetes y servicio de alimentos"),
        to: "/buscar?resourceType=service&propertyType=catering",
      },
      {
        icon: Wrench,
        label: t("nav.dropdown.serviceMaintenance", "Mantenimiento"),
        desc: t("nav.dropdown.serviceMaintenanceDesc", "Reparaciones y mantenimiento general"),
        to: "/buscar?resourceType=service&propertyType=maintenance",
      },
    ],
  },
  {
    name: t("nav.experiences", "Experiencias"),
    path: "/buscar?resourceType=experience",
    items: [
      {
        icon: Map,
        label: t("nav.dropdown.experienceTour", "Tours"),
        desc: t("nav.dropdown.experienceTourDesc", "Recorridos guiados por la zona"),
        to: "/buscar?resourceType=experience&propertyType=tour",
      },
      {
        icon: GraduationCap,
        label: t("nav.dropdown.experienceClass", "Clases"),
        desc: t("nav.dropdown.experienceClassDesc", "Clases y cursos especializados"),
        to: "/buscar?resourceType=experience&propertyType=class",
      },
      {
        icon: Hammer,
        label: t("nav.dropdown.experienceWorkshop", "Talleres"),
        desc: t("nav.dropdown.experienceWorkshopDesc", "Talleres creativos y prácticos"),
        to: "/buscar?resourceType=experience&propertyType=workshop",
      },
      {
        icon: Mountain,
        label: t("nav.dropdown.experienceAdventure", "Aventura"),
        desc: t("nav.dropdown.experienceAdventureDesc", "Actividades al aire libre y deportes"),
        to: "/buscar?resourceType=experience&propertyType=adventure",
      },
      {
        icon: Heart,
        label: t("nav.dropdown.experienceWellness", "Bienestar"),
        desc: t("nav.dropdown.experienceWellnessDesc", "Spa, yoga y relajación"),
        to: "/buscar?resourceType=experience&propertyType=wellness",
      },
      {
        icon: Wine,
        label: t("nav.dropdown.experienceGastronomy", "Gastronomía"),
        desc: t("nav.dropdown.experienceGastronomyDesc", "Catas, degustaciones y food tours"),
        to: "/buscar?resourceType=experience&propertyType=gastronomy",
      },
    ],
  },
  {
    name: t("nav.venues", "Salones y Espacios"),
    path: "/buscar?resourceType=venue",
    items: [
      {
        icon: PartyPopper,
        label: t("nav.dropdown.venueEventHall", "Salones de eventos"),
        desc: t("nav.dropdown.venueEventHallDesc", "Salones para bodas, XV años y más"),
        to: "/buscar?resourceType=venue&propertyType=event_hall",
      },
      {
        icon: Store,
        label: t("nav.dropdown.venueCommercialLocal", "Locales comerciales"),
        desc: t("nav.dropdown.venueCommercialLocalDesc", "Espacios para tu negocio"),
        to: "/buscar?resourceType=venue&propertyType=commercial_local",
      },
      {
        icon: Clapperboard,
        label: t("nav.dropdown.venueStudio", "Estudios"),
        desc: t("nav.dropdown.venueStudioDesc", "Estudios de grabación y producción"),
        to: "/buscar?resourceType=venue&propertyType=studio",
      },
      {
        icon: Laptop,
        label: t("nav.dropdown.venueCoworking", "Coworking"),
        desc: t("nav.dropdown.venueCoworkingDesc", "Espacios de trabajo compartido"),
        to: "/buscar?resourceType=venue&propertyType=coworking",
      },
      {
        icon: Users,
        label: t("nav.dropdown.venueMeetingRoom", "Salas de juntas"),
        desc: t("nav.dropdown.venueMeetingRoomDesc", "Salas equipadas para reuniones"),
        to: "/buscar?resourceType=venue&propertyType=meeting_room",
      },
    ],
  },
];
